name: warehouse
description: >
  A multi-model database to object mapper
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
#dependencies:
#  lib_name: any
#dev_dependencies:
#  unittest: any
