name: warehouse
description: >
  A database to object mapper
version: 0.1.1
author: Rasmus Eneman <rasmus@eneamn.eu>
homepage: https://github.com/Pajn/Warehouse
dependencies:
  constrain: '>=0.2.0+2 <0.3.0'
  quiver: '>=0.20.0<0.22.0'
dev_dependencies:
  guinness: any
  unittest: any
